.TH BOOTSTRAPINGPROJECT "1"
.SH NAME
Bootstrapingproject \- Program description.
.SH SYNOPSIS
bootstrapingproject [\fIoptions\fR]
.SH OPTIONS
.TP
\fB\-d\fR \fB\-\-debug\fR
Enable debug level logging
.SH HOMEPAGE
For more information, please visit https://github.com/gwenp/GitRepoAdress
.SH AUTHORS
Gwenaël Pluchon <gwenael.pluchon@gmail.com>