/* AbstractMain.c generated by valac 0.20.1, the Vala compiler
 * generated from AbstractMain.vala, do not modify */

/**/
/*  Copyright (C) 2011-2012 Gwenaël Pluchon*/
/**/
/*  This program is free software: you can redistribute it and/or modify*/
/*  it under the terms of the GNU General Public License as published by*/
/*  the Free Software Foundation, either version 3 of the License, or*/
/*  (at your option) any later version.*/
/**/
/*  This program is distributed in the hope that it will be useful,*/
/*  but WITHOUT ANY WARRANTY; without even the implied warranty of*/
/*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the*/
/*  GNU General Public License for more details.*/
/**/
/*  You should have received a copy of the GNU General Public License*/
/*  along with this program.  If not, see <http://www.gnu.org/licenses/>.*/
/**/

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>
#include <gdk/gdk.h>
#include <signal.h>
#include <sys/utsname.h>
#include <libwnck/libwnck.h>
#include <cairo.h>
#include <pango/pango.h>
#include <gio/gio.h>


#define BOOTSTRAPINGPROJECT_FACTORIES_TYPE_ABSTRACT_MAIN (bootstrapingproject_factories_abstract_main_get_type ())
#define BOOTSTRAPINGPROJECT_FACTORIES_ABSTRACT_MAIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOOTSTRAPINGPROJECT_FACTORIES_TYPE_ABSTRACT_MAIN, BootstrapingprojectFactoriesAbstractMain))
#define BOOTSTRAPINGPROJECT_FACTORIES_ABSTRACT_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOOTSTRAPINGPROJECT_FACTORIES_TYPE_ABSTRACT_MAIN, BootstrapingprojectFactoriesAbstractMainClass))
#define BOOTSTRAPINGPROJECT_FACTORIES_IS_ABSTRACT_MAIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOOTSTRAPINGPROJECT_FACTORIES_TYPE_ABSTRACT_MAIN))
#define BOOTSTRAPINGPROJECT_FACTORIES_IS_ABSTRACT_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOOTSTRAPINGPROJECT_FACTORIES_TYPE_ABSTRACT_MAIN))
#define BOOTSTRAPINGPROJECT_FACTORIES_ABSTRACT_MAIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOOTSTRAPINGPROJECT_FACTORIES_TYPE_ABSTRACT_MAIN, BootstrapingprojectFactoriesAbstractMainClass))

typedef struct _BootstrapingprojectFactoriesAbstractMain BootstrapingprojectFactoriesAbstractMain;
typedef struct _BootstrapingprojectFactoriesAbstractMainClass BootstrapingprojectFactoriesAbstractMainClass;
typedef struct _BootstrapingprojectFactoriesAbstractMainPrivate BootstrapingprojectFactoriesAbstractMainPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

#define BOOTSTRAPINGPROJECT_SYSTEM_TYPE_LOG_LEVEL (bootstrapingproject_system_log_level_get_type ())
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_option_context_free0(var) ((var == NULL) ? NULL : (var = (g_option_context_free (var), NULL)))

#define BOOTSTRAPINGPROJECT_TYPE_MAIN_CONTROLLER (bootstrapingproject_main_controller_get_type ())
#define BOOTSTRAPINGPROJECT_MAIN_CONTROLLER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOOTSTRAPINGPROJECT_TYPE_MAIN_CONTROLLER, BootstrapingprojectMainController))
#define BOOTSTRAPINGPROJECT_MAIN_CONTROLLER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOOTSTRAPINGPROJECT_TYPE_MAIN_CONTROLLER, BootstrapingprojectMainControllerClass))
#define BOOTSTRAPINGPROJECT_IS_MAIN_CONTROLLER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOOTSTRAPINGPROJECT_TYPE_MAIN_CONTROLLER))
#define BOOTSTRAPINGPROJECT_IS_MAIN_CONTROLLER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOOTSTRAPINGPROJECT_TYPE_MAIN_CONTROLLER))
#define BOOTSTRAPINGPROJECT_MAIN_CONTROLLER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOOTSTRAPINGPROJECT_TYPE_MAIN_CONTROLLER, BootstrapingprojectMainControllerClass))

typedef struct _BootstrapingprojectMainController BootstrapingprojectMainController;
typedef struct _BootstrapingprojectMainControllerClass BootstrapingprojectMainControllerClass;

struct _BootstrapingprojectFactoriesAbstractMain {
	GObject parent_instance;
	BootstrapingprojectFactoriesAbstractMainPrivate * priv;
	GtkApplication* application;
	gchar* build_pkg_data_dir;
	gchar* program_name;
	gchar* exec_name;
};

struct _BootstrapingprojectFactoriesAbstractMainClass {
	GObjectClass parent_class;
	gint (*run) (BootstrapingprojectFactoriesAbstractMain* self, gchar*** args, int* args_length1);
	void (*initialize_program) (BootstrapingprojectFactoriesAbstractMain* self);
	gboolean (*initialize_libraries) (BootstrapingprojectFactoriesAbstractMain* self, gchar*** args, int* args_length1);
	void (*initialize_services) (BootstrapingprojectFactoriesAbstractMain* self);
	gboolean (*parse_commandline) (BootstrapingprojectFactoriesAbstractMain* self, gchar*** args, int* args_length1);
	void (*set_options) (BootstrapingprojectFactoriesAbstractMain* self);
	void (*create_controller) (BootstrapingprojectFactoriesAbstractMain* self);
};

typedef enum  {
	BOOTSTRAPINGPROJECT_SYSTEM_LOG_LEVEL_VERBOSE,
	BOOTSTRAPINGPROJECT_SYSTEM_LOG_LEVEL_DEBUG,
	BOOTSTRAPINGPROJECT_SYSTEM_LOG_LEVEL_INFO,
	BOOTSTRAPINGPROJECT_SYSTEM_LOG_LEVEL_NOTIFY,
	BOOTSTRAPINGPROJECT_SYSTEM_LOG_LEVEL_WARN,
	BOOTSTRAPINGPROJECT_SYSTEM_LOG_LEVEL_ERROR,
	BOOTSTRAPINGPROJECT_SYSTEM_LOG_LEVEL_FATAL
} BootstrapingprojectSystemLogLevel;


static gpointer bootstrapingproject_factories_abstract_main_parent_class = NULL;
extern gchar* bootstrapingproject_factories_abstract_main_dock_path;
gchar* bootstrapingproject_factories_abstract_main_dock_path = NULL;
extern gboolean bootstrapingproject_factories_abstract_main_DEBUG;
gboolean bootstrapingproject_factories_abstract_main_DEBUG = FALSE;
extern gboolean bootstrapingproject_factories_abstract_main_VERBOSE;
gboolean bootstrapingproject_factories_abstract_main_VERBOSE = FALSE;

GType bootstrapingproject_factories_abstract_main_get_type (void) G_GNUC_CONST;
enum  {
	BOOTSTRAPINGPROJECT_FACTORIES_ABSTRACT_MAIN_DUMMY_PROPERTY
};
gint bootstrapingproject_factories_abstract_main_run (BootstrapingprojectFactoriesAbstractMain* self, gchar*** args, int* args_length1);
static gint bootstrapingproject_factories_abstract_main_real_run (BootstrapingprojectFactoriesAbstractMain* self, gchar*** args, int* args_length1);
void bootstrapingproject_factories_abstract_main_initialize_program (BootstrapingprojectFactoriesAbstractMain* self);
gboolean bootstrapingproject_factories_abstract_main_parse_commandline (BootstrapingprojectFactoriesAbstractMain* self, gchar*** args, int* args_length1);
gboolean bootstrapingproject_factories_abstract_main_initialize_libraries (BootstrapingprojectFactoriesAbstractMain* self, gchar*** args, int* args_length1);
void bootstrapingproject_factories_abstract_main_set_options (BootstrapingprojectFactoriesAbstractMain* self);
void bootstrapingproject_factories_abstract_main_initialize_services (BootstrapingprojectFactoriesAbstractMain* self);
void bootstrapingproject_factories_abstract_main_create_controller (BootstrapingprojectFactoriesAbstractMain* self);
gint prctl (gint option, const gchar* arg2, gulong arg3, gulong arg4, gulong arg5);
static void bootstrapingproject_factories_abstract_main_real_initialize_program (BootstrapingprojectFactoriesAbstractMain* self);
static void bootstrapingproject_factories_abstract_main_sig_handler (gint sig);
static void _bootstrapingproject_factories_abstract_main_sig_handler_sighandler_t (gint signal);
void bootstrapingproject_system_logger_initialize (const gchar* app_name);
GType bootstrapingproject_system_log_level_get_type (void) G_GNUC_CONST;
BootstrapingprojectSystemLogLevel bootstrapingproject_system_logger_get_DisplayLevel (void);
void bootstrapingproject_system_logger_set_DisplayLevel (BootstrapingprojectSystemLogLevel value);
static gboolean bootstrapingproject_factories_abstract_main_real_initialize_libraries (BootstrapingprojectFactoriesAbstractMain* self, gchar*** args, int* args_length1);
static void bootstrapingproject_factories_abstract_main_real_initialize_services (BootstrapingprojectFactoriesAbstractMain* self);
void bootstrapingproject_system_paths_initialize (const gchar* app_name, const gchar* data_folder);
gboolean bootstrapingproject_system_paths_ensure_directory_exists (GFile* dir);
GFile* bootstrapingproject_system_paths_get_AppConfigFolder (void);
static gboolean bootstrapingproject_factories_abstract_main_real_parse_commandline (BootstrapingprojectFactoriesAbstractMain* self, gchar*** args, int* args_length1);
static void bootstrapingproject_factories_abstract_main_real_set_options (BootstrapingprojectFactoriesAbstractMain* self);
static void bootstrapingproject_factories_abstract_main_real_create_controller (BootstrapingprojectFactoriesAbstractMain* self);
BootstrapingprojectMainController* bootstrapingproject_main_controller_new (void);
BootstrapingprojectMainController* bootstrapingproject_main_controller_construct (GType object_type);
GType bootstrapingproject_main_controller_get_type (void) G_GNUC_CONST;
BootstrapingprojectFactoriesAbstractMain* bootstrapingproject_factories_abstract_main_construct (GType object_type);
static void bootstrapingproject_factories_abstract_main_finalize (GObject* obj);

const GOptionEntry BOOTSTRAPINGPROJECT_FACTORIES_ABSTRACT_MAIN_options[3] = {{"debug", 'd', 0, G_OPTION_ARG_NONE, &bootstrapingproject_factories_abstract_main_DEBUG, "Enable debug logging", NULL}, {"verbose", 'v', 0, G_OPTION_ARG_NONE, &bootstrapingproject_factories_abstract_main_VERBOSE, "Enable verbose logging", NULL}, {NULL}};

static gint bootstrapingproject_factories_abstract_main_real_run (BootstrapingprojectFactoriesAbstractMain* self, gchar*** args, int* args_length1) {
	gint result = 0;
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
#line 63 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	bootstrapingproject_factories_abstract_main_initialize_program (self);
#line 65 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	_tmp0_ = bootstrapingproject_factories_abstract_main_parse_commandline (self, args, args_length1);
#line 65 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	if (!_tmp0_) {
#line 66 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
		result = EXIT_FAILURE;
#line 66 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
		return result;
#line 152 "AbstractMain.c"
	}
#line 68 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	_tmp1_ = bootstrapingproject_factories_abstract_main_initialize_libraries (self, args, args_length1);
#line 68 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	if (!_tmp1_) {
#line 69 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
		result = EXIT_FAILURE;
#line 69 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
		return result;
#line 162 "AbstractMain.c"
	}
#line 71 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	bootstrapingproject_factories_abstract_main_set_options (self);
#line 73 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	bootstrapingproject_factories_abstract_main_initialize_services (self);
#line 75 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	g_signal_emit_by_name (self, "initialized");
#line 77 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	bootstrapingproject_factories_abstract_main_create_controller (self);
#line 78 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	gdk_threads_enter ();
#line 79 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	gtk_main ();
#line 80 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	gdk_threads_leave ();
#line 82 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	result = EXIT_SUCCESS;
#line 82 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	return result;
#line 182 "AbstractMain.c"
}


gint bootstrapingproject_factories_abstract_main_run (BootstrapingprojectFactoriesAbstractMain* self, gchar*** args, int* args_length1) {
#line 61 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	g_return_val_if_fail (self != NULL, 0);
#line 61 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	return BOOTSTRAPINGPROJECT_FACTORIES_ABSTRACT_MAIN_GET_CLASS (self)->run (self, args, args_length1);
#line 191 "AbstractMain.c"
}


static void _bootstrapingproject_factories_abstract_main_sig_handler_sighandler_t (gint signal) {
#line 101 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	bootstrapingproject_factories_abstract_main_sig_handler (signal);
#line 198 "AbstractMain.c"
}


static void bootstrapingproject_factories_abstract_main_real_initialize_program (BootstrapingprojectFactoriesAbstractMain* self) {
	const gchar* _tmp0_;
	const gchar* _tmp1_;
	BootstrapingprojectSystemLogLevel _tmp2_;
	BootstrapingprojectSystemLogLevel _tmp3_;
	struct utsname _tmp4_ = {0};
	const gchar* _tmp5_;
	guint _tmp6_ = 0U;
	guint _tmp7_ = 0U;
	guint _tmp8_ = 0U;
	const gchar* _tmp9_ = NULL;
	const gchar* _tmp10_ = NULL;
	BootstrapingprojectSystemLogLevel _tmp11_;
	BootstrapingprojectSystemLogLevel _tmp12_;
#line 98 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	_tmp0_ = self->exec_name;
#line 98 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	prctl (15, _tmp0_, (gulong) 0, (gulong) 0, (gulong) 0);
#line 99 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	_tmp1_ = self->exec_name;
#line 99 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	g_set_prgname (_tmp1_);
#line 101 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	signal (SIGINT, _bootstrapingproject_factories_abstract_main_sig_handler_sighandler_t);
#line 102 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	signal (SIGTERM, _bootstrapingproject_factories_abstract_main_sig_handler_sighandler_t);
#line 104 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	bootstrapingproject_system_logger_initialize ("bootstrapingproject");
#line 105 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	_tmp2_ = bootstrapingproject_system_logger_get_DisplayLevel ();
#line 105 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	_tmp3_ = _tmp2_;
#line 105 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	bootstrapingproject_system_logger_set_DisplayLevel (BOOTSTRAPINGPROJECT_SYSTEM_LOG_LEVEL_INFO);
#line 107 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	uname (&_tmp4_);
#line 107 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	_tmp5_ = _tmp4_.release;
#line 107 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	g_message ("AbstractMain.vala:107: Kernel version: %s", _tmp5_);
#line 108 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	g_message ("AbstractMain.vala:108: GLib version: %u.%u.%u", glib_major_version, glib_minor_version, glib_micro_version);
#line 109 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	_tmp6_ = gtk_get_major_version ();
#line 109 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	_tmp7_ = gtk_get_minor_version ();
#line 109 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	_tmp8_ = gtk_get_micro_version ();
#line 109 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	g_message ("AbstractMain.vala:109: GTK+ version: %u.%u.%u", _tmp6_, _tmp7_, _tmp8_);
#line 110 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	g_message ("AbstractMain.vala:110: Wnck version: %d.%d.%d", WNCK_MAJOR_VERSION, WNCK_MINOR_VERSION, WNCK_MICRO_VERSION);
#line 111 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	_tmp9_ = cairo_version_string ();
#line 111 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	g_message ("AbstractMain.vala:111: Cairo version: %s", _tmp9_);
#line 112 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	_tmp10_ = pango_version_string ();
#line 112 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	g_message ("AbstractMain.vala:112: Pango version: %s", _tmp10_);
#line 113 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	_tmp11_ = bootstrapingproject_system_logger_get_DisplayLevel ();
#line 113 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	_tmp12_ = _tmp11_;
#line 113 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	bootstrapingproject_system_logger_set_DisplayLevel (BOOTSTRAPINGPROJECT_SYSTEM_LOG_LEVEL_WARN);
#line 268 "AbstractMain.c"
}


void bootstrapingproject_factories_abstract_main_initialize_program (BootstrapingprojectFactoriesAbstractMain* self) {
#line 95 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	g_return_if_fail (self != NULL);
#line 95 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	BOOTSTRAPINGPROJECT_FACTORIES_ABSTRACT_MAIN_GET_CLASS (self)->initialize_program (self);
#line 277 "AbstractMain.c"
}


static gboolean bootstrapingproject_factories_abstract_main_real_initialize_libraries (BootstrapingprojectFactoriesAbstractMain* self, gchar*** args, int* args_length1) {
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
	GtkApplication* _tmp1_;
	GError * _inner_error_ = NULL;
#line 120 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	_tmp0_ = g_thread_supported ();
#line 120 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	if (!_tmp0_) {
#line 121 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
		g_critical ("AbstractMain.vala:121: Problem initializing thread support.");
#line 122 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
		result = FALSE;
#line 122 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
		return result;
#line 296 "AbstractMain.c"
	}
#line 125 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	gdk_threads_init ();
#line 126 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	gtk_init (args_length1, args);
#line 128 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	_tmp1_ = gtk_application_new ("testing.bootstrapingproject", G_APPLICATION_FLAGS_NONE);
#line 128 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	_g_object_unref0 (self->application);
#line 128 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	self->application = _tmp1_;
#line 308 "AbstractMain.c"
	{
		gboolean _tmp2_ = FALSE;
		GtkApplication* _tmp3_;
		gboolean _tmp4_ = FALSE;
		gboolean _tmp5_;
		gboolean _tmp8_;
#line 130 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
		_tmp3_ = self->application;
#line 130 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
		_tmp4_ = g_application_register ((GApplication*) _tmp3_, NULL, &_inner_error_);
#line 130 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
		_tmp5_ = _tmp4_;
#line 130 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
		if (_inner_error_ != NULL) {
#line 323 "AbstractMain.c"
			goto __catch0_g_error;
		}
#line 130 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
		if (_tmp5_) {
#line 328 "AbstractMain.c"
			GtkApplication* _tmp6_;
			gboolean _tmp7_ = FALSE;
#line 130 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
			_tmp6_ = self->application;
#line 130 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
			_tmp7_ = g_application_get_is_remote ((GApplication*) _tmp6_);
#line 130 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
			_tmp2_ = !_tmp7_;
#line 337 "AbstractMain.c"
		} else {
#line 130 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
			_tmp2_ = FALSE;
#line 341 "AbstractMain.c"
		}
#line 130 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
		_tmp8_ = _tmp2_;
#line 130 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
		if (_tmp8_) {
#line 131 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
			result = TRUE;
#line 131 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
			return result;
#line 351 "AbstractMain.c"
		}
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		GError* _tmp9_;
		const gchar* _tmp10_;
#line 129 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
		e = _inner_error_;
#line 129 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
		_inner_error_ = NULL;
#line 133 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
		_tmp9_ = e;
#line 133 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
		_tmp10_ = _tmp9_->message;
#line 133 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
		g_critical ("AbstractMain.vala:133: Registering application as '%s' failed. (%s)", "bootstrapingproject", _tmp10_);
#line 134 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
		result = FALSE;
#line 134 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
		_g_error_free0 (e);
#line 134 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
		return result;
#line 376 "AbstractMain.c"
	}
	__finally0:
#line 129 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	if (_inner_error_ != NULL) {
#line 129 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 129 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
		g_clear_error (&_inner_error_);
#line 129 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
		return FALSE;
#line 387 "AbstractMain.c"
	}
#line 138 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	result = FALSE;
#line 138 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	return result;
#line 393 "AbstractMain.c"
}


gboolean bootstrapingproject_factories_abstract_main_initialize_libraries (BootstrapingprojectFactoriesAbstractMain* self, gchar*** args, int* args_length1) {
#line 116 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 116 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	return BOOTSTRAPINGPROJECT_FACTORIES_ABSTRACT_MAIN_GET_CLASS (self)->initialize_libraries (self, args, args_length1);
#line 402 "AbstractMain.c"
}


/**
 * Initializes the Bootstrapingproject services.
 */
static void bootstrapingproject_factories_abstract_main_real_initialize_services (BootstrapingprojectFactoriesAbstractMain* self) {
	const gchar* _tmp0_;
	const gchar* _tmp1_;
	GFile* _tmp2_;
	GFile* _tmp3_;
	const gchar* _tmp4_;
	GFile* _tmp5_ = NULL;
	GFile* _tmp6_;
#line 146 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	_tmp0_ = self->exec_name;
#line 146 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	_tmp1_ = self->build_pkg_data_dir;
#line 146 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	bootstrapingproject_system_paths_initialize (_tmp0_, _tmp1_);
#line 147 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	_tmp2_ = bootstrapingproject_system_paths_get_AppConfigFolder ();
#line 147 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	_tmp3_ = _tmp2_;
#line 147 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	_tmp4_ = bootstrapingproject_factories_abstract_main_dock_path;
#line 147 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	_tmp5_ = g_file_get_child (_tmp3_, _tmp4_);
#line 147 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	_tmp6_ = _tmp5_;
#line 147 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	bootstrapingproject_system_paths_ensure_directory_exists (_tmp6_);
#line 147 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	_g_object_unref0 (_tmp6_);
#line 437 "AbstractMain.c"
}


void bootstrapingproject_factories_abstract_main_initialize_services (BootstrapingprojectFactoriesAbstractMain* self) {
#line 144 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	g_return_if_fail (self != NULL);
#line 144 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	BOOTSTRAPINGPROJECT_FACTORIES_ABSTRACT_MAIN_GET_CLASS (self)->initialize_services (self);
#line 446 "AbstractMain.c"
}


static void bootstrapingproject_factories_abstract_main_sig_handler (gint sig) {
	gint _tmp0_;
#line 151 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	_tmp0_ = sig;
#line 151 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	g_warning ("AbstractMain.vala:151: Caught signal (%d), exiting", _tmp0_);
#line 152 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	gtk_main_quit ();
#line 458 "AbstractMain.c"
}


/**
 * Parses the command-line for options, but does not set them.
 *
 * @param args the command-line arguments
 * @return whether the arguments were parsed successfully
 */
static gboolean bootstrapingproject_factories_abstract_main_real_parse_commandline (BootstrapingprojectFactoriesAbstractMain* self, gchar*** args, int* args_length1) {
	gboolean result = FALSE;
	GOptionContext* _tmp0_;
	GOptionContext* context;
	GOptionContext* _tmp1_;
	GOptionContext* _tmp2_;
	GOptionGroup* _tmp3_ = NULL;
	GError * _inner_error_ = NULL;
#line 183 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	_tmp0_ = g_option_context_new ("");
#line 183 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	context = _tmp0_;
#line 185 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	_tmp1_ = context;
#line 185 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	g_option_context_add_main_entries (_tmp1_, BOOTSTRAPINGPROJECT_FACTORIES_ABSTRACT_MAIN_options, NULL);
#line 186 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	_tmp2_ = context;
#line 186 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	_tmp3_ = gtk_get_option_group (FALSE);
#line 186 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	g_option_context_add_group (_tmp2_, _tmp3_);
#line 490 "AbstractMain.c"
	{
		GOptionContext* _tmp4_;
#line 189 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
		_tmp4_ = context;
#line 189 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
		g_option_context_parse (_tmp4_, args_length1, args, &_inner_error_);
#line 189 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
		if (_inner_error_ != NULL) {
#line 499 "AbstractMain.c"
			goto __catch1_g_error;
		}
	}
	goto __finally1;
	__catch1_g_error:
	{
#line 188 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
		g_clear_error (&_inner_error_);
#line 188 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
		_inner_error_ = NULL;
#line 191 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
		result = FALSE;
#line 191 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
		_g_option_context_free0 (context);
#line 191 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
		return result;
#line 516 "AbstractMain.c"
	}
	__finally1:
#line 188 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	if (_inner_error_ != NULL) {
#line 188 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
		_g_option_context_free0 (context);
#line 188 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 188 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
		g_clear_error (&_inner_error_);
#line 188 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
		return FALSE;
#line 529 "AbstractMain.c"
	}
#line 194 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	result = TRUE;
#line 194 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	_g_option_context_free0 (context);
#line 194 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	return result;
#line 537 "AbstractMain.c"
}


gboolean bootstrapingproject_factories_abstract_main_parse_commandline (BootstrapingprojectFactoriesAbstractMain* self, gchar*** args, int* args_length1) {
#line 180 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	g_return_val_if_fail (self != NULL, FALSE);
#line 180 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	return BOOTSTRAPINGPROJECT_FACTORIES_ABSTRACT_MAIN_GET_CLASS (self)->parse_commandline (self, args, args_length1);
#line 546 "AbstractMain.c"
}


/**
 * Sets options based on the parsed command-line.
 */
static void bootstrapingproject_factories_abstract_main_real_set_options (BootstrapingprojectFactoriesAbstractMain* self) {
	gboolean _tmp0_;
	gboolean _tmp3_;
#line 202 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	_tmp0_ = bootstrapingproject_factories_abstract_main_DEBUG;
#line 202 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	if (_tmp0_) {
#line 560 "AbstractMain.c"
		BootstrapingprojectSystemLogLevel _tmp1_;
		BootstrapingprojectSystemLogLevel _tmp2_;
#line 203 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
		_tmp1_ = bootstrapingproject_system_logger_get_DisplayLevel ();
#line 203 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
		_tmp2_ = _tmp1_;
#line 203 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
		bootstrapingproject_system_logger_set_DisplayLevel (BOOTSTRAPINGPROJECT_SYSTEM_LOG_LEVEL_DEBUG);
#line 569 "AbstractMain.c"
	}
#line 204 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	_tmp3_ = bootstrapingproject_factories_abstract_main_VERBOSE;
#line 204 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	if (_tmp3_) {
#line 575 "AbstractMain.c"
		BootstrapingprojectSystemLogLevel _tmp4_;
		BootstrapingprojectSystemLogLevel _tmp5_;
#line 205 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
		_tmp4_ = bootstrapingproject_system_logger_get_DisplayLevel ();
#line 205 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
		_tmp5_ = _tmp4_;
#line 205 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
		bootstrapingproject_system_logger_set_DisplayLevel (BOOTSTRAPINGPROJECT_SYSTEM_LOG_LEVEL_VERBOSE);
#line 584 "AbstractMain.c"
	}
}


void bootstrapingproject_factories_abstract_main_set_options (BootstrapingprojectFactoriesAbstractMain* self) {
#line 200 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	g_return_if_fail (self != NULL);
#line 200 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	BOOTSTRAPINGPROJECT_FACTORIES_ABSTRACT_MAIN_GET_CLASS (self)->set_options (self);
#line 594 "AbstractMain.c"
}


/**
 * Creates the dock controller.
 */
static void bootstrapingproject_factories_abstract_main_real_create_controller (BootstrapingprojectFactoriesAbstractMain* self) {
	BootstrapingprojectMainController* _tmp0_;
	BootstrapingprojectMainController* _tmp1_;
#line 213 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	_tmp0_ = bootstrapingproject_main_controller_new ();
#line 213 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	_tmp1_ = _tmp0_;
#line 213 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	_g_object_unref0 (_tmp1_);
#line 610 "AbstractMain.c"
}


void bootstrapingproject_factories_abstract_main_create_controller (BootstrapingprojectFactoriesAbstractMain* self) {
#line 211 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	g_return_if_fail (self != NULL);
#line 211 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	BOOTSTRAPINGPROJECT_FACTORIES_ABSTRACT_MAIN_GET_CLASS (self)->create_controller (self);
#line 619 "AbstractMain.c"
}


BootstrapingprojectFactoriesAbstractMain* bootstrapingproject_factories_abstract_main_construct (GType object_type) {
	BootstrapingprojectFactoriesAbstractMain * self = NULL;
#line 29 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	self = (BootstrapingprojectFactoriesAbstractMain*) g_object_new (object_type, NULL);
#line 29 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	return self;
#line 629 "AbstractMain.c"
}


static void bootstrapingproject_factories_abstract_main_class_init (BootstrapingprojectFactoriesAbstractMainClass * klass) {
	gchar* _tmp0_;
#line 29 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	bootstrapingproject_factories_abstract_main_parent_class = g_type_class_peek_parent (klass);
#line 29 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	BOOTSTRAPINGPROJECT_FACTORIES_ABSTRACT_MAIN_CLASS (klass)->run = bootstrapingproject_factories_abstract_main_real_run;
#line 29 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	BOOTSTRAPINGPROJECT_FACTORIES_ABSTRACT_MAIN_CLASS (klass)->initialize_program = bootstrapingproject_factories_abstract_main_real_initialize_program;
#line 29 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	BOOTSTRAPINGPROJECT_FACTORIES_ABSTRACT_MAIN_CLASS (klass)->initialize_libraries = bootstrapingproject_factories_abstract_main_real_initialize_libraries;
#line 29 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	BOOTSTRAPINGPROJECT_FACTORIES_ABSTRACT_MAIN_CLASS (klass)->initialize_services = bootstrapingproject_factories_abstract_main_real_initialize_services;
#line 29 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	BOOTSTRAPINGPROJECT_FACTORIES_ABSTRACT_MAIN_CLASS (klass)->parse_commandline = bootstrapingproject_factories_abstract_main_real_parse_commandline;
#line 29 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	BOOTSTRAPINGPROJECT_FACTORIES_ABSTRACT_MAIN_CLASS (klass)->set_options = bootstrapingproject_factories_abstract_main_real_set_options;
#line 29 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	BOOTSTRAPINGPROJECT_FACTORIES_ABSTRACT_MAIN_CLASS (klass)->create_controller = bootstrapingproject_factories_abstract_main_real_create_controller;
#line 29 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	G_OBJECT_CLASS (klass)->finalize = bootstrapingproject_factories_abstract_main_finalize;
#line 653 "AbstractMain.c"
	/**
	 * Signal fired when the program is fully initialized, before creating and showing the dock.
	 */
#line 29 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	g_signal_new ("initialized", BOOTSTRAPINGPROJECT_FACTORIES_TYPE_ABSTRACT_MAIN, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
#line 45 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	_tmp0_ = g_strdup ("dock1");
#line 45 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	bootstrapingproject_factories_abstract_main_dock_path = _tmp0_;
#line 663 "AbstractMain.c"
}


static void bootstrapingproject_factories_abstract_main_instance_init (BootstrapingprojectFactoriesAbstractMain * self) {
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
#line 50 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	_tmp0_ = g_strdup ("");
#line 50 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	self->build_pkg_data_dir = _tmp0_;
#line 55 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	_tmp1_ = g_strdup ("");
#line 55 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	self->program_name = _tmp1_;
#line 59 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	_tmp2_ = g_strdup ("");
#line 59 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	self->exec_name = _tmp2_;
#line 683 "AbstractMain.c"
}


static void bootstrapingproject_factories_abstract_main_finalize (GObject* obj) {
	BootstrapingprojectFactoriesAbstractMain * self;
#line 29 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, BOOTSTRAPINGPROJECT_FACTORIES_TYPE_ABSTRACT_MAIN, BootstrapingprojectFactoriesAbstractMain);
#line 35 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	_g_object_unref0 (self->application);
#line 50 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	_g_free0 (self->build_pkg_data_dir);
#line 55 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	_g_free0 (self->program_name);
#line 59 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	_g_free0 (self->exec_name);
#line 29 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/AbstractMain.vala"
	G_OBJECT_CLASS (bootstrapingproject_factories_abstract_main_parent_class)->finalize (obj);
#line 701 "AbstractMain.c"
}


/**
 * The main class for all dock applications.  All docks should extend this class.
 * In the constructor, the string fields should be initialized to customize the dock.
 */
GType bootstrapingproject_factories_abstract_main_get_type (void) {
	static volatile gsize bootstrapingproject_factories_abstract_main_type_id__volatile = 0;
	if (g_once_init_enter (&bootstrapingproject_factories_abstract_main_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (BootstrapingprojectFactoriesAbstractMainClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) bootstrapingproject_factories_abstract_main_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (BootstrapingprojectFactoriesAbstractMain), 0, (GInstanceInitFunc) bootstrapingproject_factories_abstract_main_instance_init, NULL };
		GType bootstrapingproject_factories_abstract_main_type_id;
		bootstrapingproject_factories_abstract_main_type_id = g_type_register_static (G_TYPE_OBJECT, "BootstrapingprojectFactoriesAbstractMain", &g_define_type_info, G_TYPE_FLAG_ABSTRACT);
		g_once_init_leave (&bootstrapingproject_factories_abstract_main_type_id__volatile, bootstrapingproject_factories_abstract_main_type_id);
	}
	return bootstrapingproject_factories_abstract_main_type_id__volatile;
}



