/* Factory.c generated by valac 0.20.1, the Vala compiler
 * generated from Factory.vala, do not modify */

/**/
/*  Copyright (C) 2011 Robert Dyer*/
/**/
/*  This program is free software: you can redistribute it and/or modify*/
/*  it under the terms of the GNU General Public License as published by*/
/*  the Free Software Foundation, either version 3 of the License, or*/
/*  (at your option) any later version.*/
/**/
/*  This program is distributed in the hope that it will be useful,*/
/*  but WITHOUT ANY WARRANTY; without even the implied warranty of*/
/*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the*/
/*  GNU General Public License for more details.*/
/**/
/*  You should have received a copy of the GNU General Public License*/
/*  along with this program.  If not, see <http://www.gnu.org/licenses/>.*/
/**/

#include <glib.h>
#include <glib-object.h>


#define BOOTSTRAPINGPROJECT_FACTORIES_TYPE_FACTORY (bootstrapingproject_factories_factory_get_type ())
#define BOOTSTRAPINGPROJECT_FACTORIES_FACTORY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOOTSTRAPINGPROJECT_FACTORIES_TYPE_FACTORY, BootstrapingprojectFactoriesFactory))
#define BOOTSTRAPINGPROJECT_FACTORIES_FACTORY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOOTSTRAPINGPROJECT_FACTORIES_TYPE_FACTORY, BootstrapingprojectFactoriesFactoryClass))
#define BOOTSTRAPINGPROJECT_FACTORIES_IS_FACTORY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOOTSTRAPINGPROJECT_FACTORIES_TYPE_FACTORY))
#define BOOTSTRAPINGPROJECT_FACTORIES_IS_FACTORY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOOTSTRAPINGPROJECT_FACTORIES_TYPE_FACTORY))
#define BOOTSTRAPINGPROJECT_FACTORIES_FACTORY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOOTSTRAPINGPROJECT_FACTORIES_TYPE_FACTORY, BootstrapingprojectFactoriesFactoryClass))

typedef struct _BootstrapingprojectFactoriesFactory BootstrapingprojectFactoriesFactory;
typedef struct _BootstrapingprojectFactoriesFactoryClass BootstrapingprojectFactoriesFactoryClass;
typedef struct _BootstrapingprojectFactoriesFactoryPrivate BootstrapingprojectFactoriesFactoryPrivate;

#define BOOTSTRAPINGPROJECT_FACTORIES_TYPE_ABSTRACT_MAIN (bootstrapingproject_factories_abstract_main_get_type ())
#define BOOTSTRAPINGPROJECT_FACTORIES_ABSTRACT_MAIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOOTSTRAPINGPROJECT_FACTORIES_TYPE_ABSTRACT_MAIN, BootstrapingprojectFactoriesAbstractMain))
#define BOOTSTRAPINGPROJECT_FACTORIES_ABSTRACT_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOOTSTRAPINGPROJECT_FACTORIES_TYPE_ABSTRACT_MAIN, BootstrapingprojectFactoriesAbstractMainClass))
#define BOOTSTRAPINGPROJECT_FACTORIES_IS_ABSTRACT_MAIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOOTSTRAPINGPROJECT_FACTORIES_TYPE_ABSTRACT_MAIN))
#define BOOTSTRAPINGPROJECT_FACTORIES_IS_ABSTRACT_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOOTSTRAPINGPROJECT_FACTORIES_TYPE_ABSTRACT_MAIN))
#define BOOTSTRAPINGPROJECT_FACTORIES_ABSTRACT_MAIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOOTSTRAPINGPROJECT_FACTORIES_TYPE_ABSTRACT_MAIN, BootstrapingprojectFactoriesAbstractMainClass))

typedef struct _BootstrapingprojectFactoriesAbstractMain BootstrapingprojectFactoriesAbstractMain;
typedef struct _BootstrapingprojectFactoriesAbstractMainClass BootstrapingprojectFactoriesAbstractMainClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _BootstrapingprojectFactoriesFactory {
	GObject parent_instance;
	BootstrapingprojectFactoriesFactoryPrivate * priv;
};

struct _BootstrapingprojectFactoriesFactoryClass {
	GObjectClass parent_class;
};


static gpointer bootstrapingproject_factories_factory_parent_class = NULL;
extern BootstrapingprojectFactoriesAbstractMain* bootstrapingproject_factories_factory_main;
BootstrapingprojectFactoriesAbstractMain* bootstrapingproject_factories_factory_main = NULL;

GType bootstrapingproject_factories_factory_get_type (void) G_GNUC_CONST;
enum  {
	BOOTSTRAPINGPROJECT_FACTORIES_FACTORY_DUMMY_PROPERTY
};
GType bootstrapingproject_factories_abstract_main_get_type (void) G_GNUC_CONST;
void bootstrapingproject_factories_factory_init (BootstrapingprojectFactoriesAbstractMain* main_class);
BootstrapingprojectFactoriesFactory* bootstrapingproject_factories_factory_new (void);
BootstrapingprojectFactoriesFactory* bootstrapingproject_factories_factory_construct (GType object_type);
static void bootstrapingproject_factories_factory_finalize (GObject* obj);


static gpointer _g_object_ref0 (gpointer self) {
#line 32 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/Factory.vala"
	return self ? g_object_ref (self) : NULL;
#line 76 "Factory.c"
}


void bootstrapingproject_factories_factory_init (BootstrapingprojectFactoriesAbstractMain* main_class) {
	BootstrapingprojectFactoriesAbstractMain* _tmp0_;
	BootstrapingprojectFactoriesAbstractMain* _tmp1_;
#line 30 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/Factory.vala"
	g_return_if_fail (main_class != NULL);
#line 32 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/Factory.vala"
	_tmp0_ = main_class;
#line 32 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/Factory.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 32 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/Factory.vala"
	_g_object_unref0 (bootstrapingproject_factories_factory_main);
#line 32 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/Factory.vala"
	bootstrapingproject_factories_factory_main = _tmp1_;
#line 93 "Factory.c"
}


BootstrapingprojectFactoriesFactory* bootstrapingproject_factories_factory_construct (GType object_type) {
	BootstrapingprojectFactoriesFactory * self = NULL;
#line 23 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/Factory.vala"
	self = (BootstrapingprojectFactoriesFactory*) g_object_new (object_type, NULL);
#line 23 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/Factory.vala"
	return self;
#line 103 "Factory.c"
}


BootstrapingprojectFactoriesFactory* bootstrapingproject_factories_factory_new (void) {
#line 23 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/Factory.vala"
	return bootstrapingproject_factories_factory_construct (BOOTSTRAPINGPROJECT_FACTORIES_TYPE_FACTORY);
#line 110 "Factory.c"
}


static void bootstrapingproject_factories_factory_class_init (BootstrapingprojectFactoriesFactoryClass * klass) {
#line 23 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/Factory.vala"
	bootstrapingproject_factories_factory_parent_class = g_type_class_peek_parent (klass);
#line 23 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/Factory.vala"
	G_OBJECT_CLASS (klass)->finalize = bootstrapingproject_factories_factory_finalize;
#line 119 "Factory.c"
}


static void bootstrapingproject_factories_factory_instance_init (BootstrapingprojectFactoriesFactory * self) {
}


static void bootstrapingproject_factories_factory_finalize (GObject* obj) {
	BootstrapingprojectFactoriesFactory * self;
#line 23 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/Factory.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, BOOTSTRAPINGPROJECT_FACTORIES_TYPE_FACTORY, BootstrapingprojectFactoriesFactory);
#line 23 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Factories/Factory.vala"
	G_OBJECT_CLASS (bootstrapingproject_factories_factory_parent_class)->finalize (obj);
#line 133 "Factory.c"
}


/**
 * The main factory class for the dock.
 */
GType bootstrapingproject_factories_factory_get_type (void) {
	static volatile gsize bootstrapingproject_factories_factory_type_id__volatile = 0;
	if (g_once_init_enter (&bootstrapingproject_factories_factory_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (BootstrapingprojectFactoriesFactoryClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) bootstrapingproject_factories_factory_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (BootstrapingprojectFactoriesFactory), 0, (GInstanceInitFunc) bootstrapingproject_factories_factory_instance_init, NULL };
		GType bootstrapingproject_factories_factory_type_id;
		bootstrapingproject_factories_factory_type_id = g_type_register_static (G_TYPE_OBJECT, "BootstrapingprojectFactoriesFactory", &g_define_type_info, 0);
		g_once_init_leave (&bootstrapingproject_factories_factory_type_id__volatile, bootstrapingproject_factories_factory_type_id);
	}
	return bootstrapingproject_factories_factory_type_id__volatile;
}



