/* MainWindow.c generated by valac 0.20.1, the Vala compiler
 * generated from MainWindow.vala, do not modify */

/**/
/*  Copyright (C) 2011-2012 Robert Dyer, Michal Hruby, Rico Tzschichholz*/
/**/
/*  This program is free software: you can redistribute it and/or modify*/
/*  it under the terms of the GNU General Public License as published by*/
/*  the Free Software Foundation, either version 3 of the License, or*/
/*  (at your option) any later version.*/
/**/
/*  This program is distributed in the hope that it will be useful,*/
/*  but WITHOUT ANY WARRANTY; without even the implied warranty of*/
/*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the*/
/*  GNU General Public License for more details.*/
/**/
/*  You should have received a copy of the GNU General Public License*/
/*  along with this program.  If not, see <http://www.gnu.org/licenses/>.*/
/**/

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>


#define BOOTSTRAPINGPROJECT_WIDGETS_TYPE_MAIN_WINDOW (bootstrapingproject_widgets_main_window_get_type ())
#define BOOTSTRAPINGPROJECT_WIDGETS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOOTSTRAPINGPROJECT_WIDGETS_TYPE_MAIN_WINDOW, BootstrapingprojectWidgetsMainWindow))
#define BOOTSTRAPINGPROJECT_WIDGETS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOOTSTRAPINGPROJECT_WIDGETS_TYPE_MAIN_WINDOW, BootstrapingprojectWidgetsMainWindowClass))
#define BOOTSTRAPINGPROJECT_WIDGETS_IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOOTSTRAPINGPROJECT_WIDGETS_TYPE_MAIN_WINDOW))
#define BOOTSTRAPINGPROJECT_WIDGETS_IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOOTSTRAPINGPROJECT_WIDGETS_TYPE_MAIN_WINDOW))
#define BOOTSTRAPINGPROJECT_WIDGETS_MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOOTSTRAPINGPROJECT_WIDGETS_TYPE_MAIN_WINDOW, BootstrapingprojectWidgetsMainWindowClass))

typedef struct _BootstrapingprojectWidgetsMainWindow BootstrapingprojectWidgetsMainWindow;
typedef struct _BootstrapingprojectWidgetsMainWindowClass BootstrapingprojectWidgetsMainWindowClass;
typedef struct _BootstrapingprojectWidgetsMainWindowPrivate BootstrapingprojectWidgetsMainWindowPrivate;

#define BOOTSTRAPINGPROJECT_TYPE_MAIN_CONTROLLER (bootstrapingproject_main_controller_get_type ())
#define BOOTSTRAPINGPROJECT_MAIN_CONTROLLER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOOTSTRAPINGPROJECT_TYPE_MAIN_CONTROLLER, BootstrapingprojectMainController))
#define BOOTSTRAPINGPROJECT_MAIN_CONTROLLER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOOTSTRAPINGPROJECT_TYPE_MAIN_CONTROLLER, BootstrapingprojectMainControllerClass))
#define BOOTSTRAPINGPROJECT_IS_MAIN_CONTROLLER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOOTSTRAPINGPROJECT_TYPE_MAIN_CONTROLLER))
#define BOOTSTRAPINGPROJECT_IS_MAIN_CONTROLLER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOOTSTRAPINGPROJECT_TYPE_MAIN_CONTROLLER))
#define BOOTSTRAPINGPROJECT_MAIN_CONTROLLER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOOTSTRAPINGPROJECT_TYPE_MAIN_CONTROLLER, BootstrapingprojectMainControllerClass))

typedef struct _BootstrapingprojectMainController BootstrapingprojectMainController;
typedef struct _BootstrapingprojectMainControllerClass BootstrapingprojectMainControllerClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _BootstrapingprojectWidgetsMainWindow {
	GtkWindow parent_instance;
	BootstrapingprojectWidgetsMainWindowPrivate * priv;
};

struct _BootstrapingprojectWidgetsMainWindowClass {
	GtkWindowClass parent_class;
};

struct _BootstrapingprojectWidgetsMainWindowPrivate {
	BootstrapingprojectMainController* _controller;
};


static gpointer bootstrapingproject_widgets_main_window_parent_class = NULL;

GType bootstrapingproject_widgets_main_window_get_type (void) G_GNUC_CONST;
GType bootstrapingproject_main_controller_get_type (void) G_GNUC_CONST;
#define BOOTSTRAPINGPROJECT_WIDGETS_MAIN_WINDOW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), BOOTSTRAPINGPROJECT_WIDGETS_TYPE_MAIN_WINDOW, BootstrapingprojectWidgetsMainWindowPrivate))
enum  {
	BOOTSTRAPINGPROJECT_WIDGETS_MAIN_WINDOW_DUMMY_PROPERTY,
	BOOTSTRAPINGPROJECT_WIDGETS_MAIN_WINDOW_CONTROLLER
};
BootstrapingprojectWidgetsMainWindow* bootstrapingproject_widgets_main_window_new (BootstrapingprojectMainController* controller);
BootstrapingprojectWidgetsMainWindow* bootstrapingproject_widgets_main_window_construct (GType object_type, BootstrapingprojectMainController* controller);
static BootstrapingprojectMainController* bootstrapingproject_widgets_main_window_get_controller (BootstrapingprojectWidgetsMainWindow* self);
static void bootstrapingproject_widgets_main_window_set_controller (BootstrapingprojectWidgetsMainWindow* self, BootstrapingprojectMainController* value);
static GObject * bootstrapingproject_widgets_main_window_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void bootstrapingproject_widgets_main_window_finalize (GObject* obj);
static void _vala_bootstrapingproject_widgets_main_window_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_bootstrapingproject_widgets_main_window_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


/**
 * Creates a new dock window.
 */
BootstrapingprojectWidgetsMainWindow* bootstrapingproject_widgets_main_window_construct (GType object_type, BootstrapingprojectMainController* controller) {
	BootstrapingprojectWidgetsMainWindow * self = NULL;
	BootstrapingprojectMainController* _tmp0_;
#line 42 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Widgets/MainWindow.vala"
	g_return_val_if_fail (controller != NULL, NULL);
#line 44 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Widgets/MainWindow.vala"
	_tmp0_ = controller;
#line 44 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Widgets/MainWindow.vala"
	self = (BootstrapingprojectWidgetsMainWindow*) g_object_new (object_type, "controller", _tmp0_, "type", GTK_WINDOW_TOPLEVEL, NULL);
#line 42 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Widgets/MainWindow.vala"
	return self;
#line 96 "MainWindow.c"
}


BootstrapingprojectWidgetsMainWindow* bootstrapingproject_widgets_main_window_new (BootstrapingprojectMainController* controller) {
#line 42 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Widgets/MainWindow.vala"
	return bootstrapingproject_widgets_main_window_construct (BOOTSTRAPINGPROJECT_WIDGETS_TYPE_MAIN_WINDOW, controller);
#line 103 "MainWindow.c"
}


static BootstrapingprojectMainController* bootstrapingproject_widgets_main_window_get_controller (BootstrapingprojectWidgetsMainWindow* self) {
	BootstrapingprojectMainController* result;
	BootstrapingprojectMainController* _tmp0_;
#line 37 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Widgets/MainWindow.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 37 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Widgets/MainWindow.vala"
	_tmp0_ = self->priv->_controller;
#line 37 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Widgets/MainWindow.vala"
	result = _tmp0_;
#line 37 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Widgets/MainWindow.vala"
	return result;
#line 118 "MainWindow.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 37 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Widgets/MainWindow.vala"
	return self ? g_object_ref (self) : NULL;
#line 125 "MainWindow.c"
}


static void bootstrapingproject_widgets_main_window_set_controller (BootstrapingprojectWidgetsMainWindow* self, BootstrapingprojectMainController* value) {
	BootstrapingprojectMainController* _tmp0_;
	BootstrapingprojectMainController* _tmp1_;
#line 37 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Widgets/MainWindow.vala"
	g_return_if_fail (self != NULL);
#line 37 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Widgets/MainWindow.vala"
	_tmp0_ = value;
#line 37 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Widgets/MainWindow.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 37 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Widgets/MainWindow.vala"
	_g_object_unref0 (self->priv->_controller);
#line 37 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Widgets/MainWindow.vala"
	self->priv->_controller = _tmp1_;
#line 37 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Widgets/MainWindow.vala"
	g_object_notify ((GObject *) self, "controller");
#line 144 "MainWindow.c"
}


static GObject * bootstrapingproject_widgets_main_window_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	BootstrapingprojectWidgetsMainWindow * self;
#line 47 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Widgets/MainWindow.vala"
	parent_class = G_OBJECT_CLASS (bootstrapingproject_widgets_main_window_parent_class);
#line 47 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Widgets/MainWindow.vala"
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
#line 47 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Widgets/MainWindow.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, BOOTSTRAPINGPROJECT_WIDGETS_TYPE_MAIN_WINDOW, BootstrapingprojectWidgetsMainWindow);
#line 47 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Widgets/MainWindow.vala"
	return obj;
#line 160 "MainWindow.c"
}


static void bootstrapingproject_widgets_main_window_class_init (BootstrapingprojectWidgetsMainWindowClass * klass) {
#line 31 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Widgets/MainWindow.vala"
	bootstrapingproject_widgets_main_window_parent_class = g_type_class_peek_parent (klass);
#line 31 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Widgets/MainWindow.vala"
	g_type_class_add_private (klass, sizeof (BootstrapingprojectWidgetsMainWindowPrivate));
#line 31 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Widgets/MainWindow.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_bootstrapingproject_widgets_main_window_get_property;
#line 31 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Widgets/MainWindow.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_bootstrapingproject_widgets_main_window_set_property;
#line 31 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Widgets/MainWindow.vala"
	G_OBJECT_CLASS (klass)->constructor = bootstrapingproject_widgets_main_window_constructor;
#line 31 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Widgets/MainWindow.vala"
	G_OBJECT_CLASS (klass)->finalize = bootstrapingproject_widgets_main_window_finalize;
#line 177 "MainWindow.c"
	/**
	 * The controller for this window.
	 */
#line 31 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Widgets/MainWindow.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), BOOTSTRAPINGPROJECT_WIDGETS_MAIN_WINDOW_CONTROLLER, g_param_spec_object ("controller", "controller", "controller", BOOTSTRAPINGPROJECT_TYPE_MAIN_CONTROLLER, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_WRITABLE | G_PARAM_CONSTRUCT_ONLY));
#line 183 "MainWindow.c"
}


static void bootstrapingproject_widgets_main_window_instance_init (BootstrapingprojectWidgetsMainWindow * self) {
#line 31 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Widgets/MainWindow.vala"
	self->priv = BOOTSTRAPINGPROJECT_WIDGETS_MAIN_WINDOW_GET_PRIVATE (self);
#line 190 "MainWindow.c"
}


static void bootstrapingproject_widgets_main_window_finalize (GObject* obj) {
	BootstrapingprojectWidgetsMainWindow * self;
#line 31 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Widgets/MainWindow.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, BOOTSTRAPINGPROJECT_WIDGETS_TYPE_MAIN_WINDOW, BootstrapingprojectWidgetsMainWindow);
#line 37 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Widgets/MainWindow.vala"
	_g_object_unref0 (self->priv->_controller);
#line 31 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Widgets/MainWindow.vala"
	G_OBJECT_CLASS (bootstrapingproject_widgets_main_window_parent_class)->finalize (obj);
#line 202 "MainWindow.c"
}


/**
 * The main window for all docks.
 */
GType bootstrapingproject_widgets_main_window_get_type (void) {
	static volatile gsize bootstrapingproject_widgets_main_window_type_id__volatile = 0;
	if (g_once_init_enter (&bootstrapingproject_widgets_main_window_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (BootstrapingprojectWidgetsMainWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) bootstrapingproject_widgets_main_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (BootstrapingprojectWidgetsMainWindow), 0, (GInstanceInitFunc) bootstrapingproject_widgets_main_window_instance_init, NULL };
		GType bootstrapingproject_widgets_main_window_type_id;
		bootstrapingproject_widgets_main_window_type_id = g_type_register_static (GTK_TYPE_WINDOW, "BootstrapingprojectWidgetsMainWindow", &g_define_type_info, 0);
		g_once_init_leave (&bootstrapingproject_widgets_main_window_type_id__volatile, bootstrapingproject_widgets_main_window_type_id);
	}
	return bootstrapingproject_widgets_main_window_type_id__volatile;
}


static void _vala_bootstrapingproject_widgets_main_window_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	BootstrapingprojectWidgetsMainWindow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, BOOTSTRAPINGPROJECT_WIDGETS_TYPE_MAIN_WINDOW, BootstrapingprojectWidgetsMainWindow);
#line 31 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Widgets/MainWindow.vala"
	switch (property_id) {
#line 31 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Widgets/MainWindow.vala"
		case BOOTSTRAPINGPROJECT_WIDGETS_MAIN_WINDOW_CONTROLLER:
#line 31 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Widgets/MainWindow.vala"
		g_value_set_object (value, bootstrapingproject_widgets_main_window_get_controller (self));
#line 31 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Widgets/MainWindow.vala"
		break;
#line 232 "MainWindow.c"
		default:
#line 31 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Widgets/MainWindow.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 31 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Widgets/MainWindow.vala"
		break;
#line 238 "MainWindow.c"
	}
}


static void _vala_bootstrapingproject_widgets_main_window_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	BootstrapingprojectWidgetsMainWindow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, BOOTSTRAPINGPROJECT_WIDGETS_TYPE_MAIN_WINDOW, BootstrapingprojectWidgetsMainWindow);
#line 31 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Widgets/MainWindow.vala"
	switch (property_id) {
#line 31 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Widgets/MainWindow.vala"
		case BOOTSTRAPINGPROJECT_WIDGETS_MAIN_WINDOW_CONTROLLER:
#line 31 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Widgets/MainWindow.vala"
		bootstrapingproject_widgets_main_window_set_controller (self, g_value_get_object (value));
#line 31 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Widgets/MainWindow.vala"
		break;
#line 254 "MainWindow.c"
		default:
#line 31 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Widgets/MainWindow.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 31 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/Widgets/MainWindow.vala"
		break;
#line 260 "MainWindow.c"
	}
}



