/* AppMain.c generated by valac 0.20.1, the Vala compiler
 * generated from AppMain.vala, do not modify */

/**/
/*  Copyright (C) 2011-2012 Gwenaël Pluchon*/
/**/
/*  This program is free software: you can redistribute it and/or modify*/
/*  it under the terms of the GNU General Public License as published by*/
/*  the Free Software Foundation, either version 3 of the License, or*/
/*  (at your option) any later version.*/
/**/
/*  This program is distributed in the hope that it will be useful,*/
/*  but WITHOUT ANY WARRANTY; without even the implied warranty of*/
/*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the*/
/*  GNU General Public License for more details.*/
/**/
/*  You should have received a copy of the GNU General Public License*/
/*  along with this program.  If not, see <http://www.gnu.org/licenses/>.*/
/**/

#include <glib.h>
#include <glib-object.h>
#include "bootstrapingproject.h"
#include <stdlib.h>
#include <string.h>
#include "config.h"


#define APP_MAIN_TYPE_APP_MAIN (app_main_app_main_get_type ())
#define APP_MAIN_APP_MAIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), APP_MAIN_TYPE_APP_MAIN, AppMainAppMain))
#define APP_MAIN_APP_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), APP_MAIN_TYPE_APP_MAIN, AppMainAppMainClass))
#define APP_MAIN_IS_APP_MAIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), APP_MAIN_TYPE_APP_MAIN))
#define APP_MAIN_IS_APP_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), APP_MAIN_TYPE_APP_MAIN))
#define APP_MAIN_APP_MAIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), APP_MAIN_TYPE_APP_MAIN, AppMainAppMainClass))

typedef struct _AppMainAppMain AppMainAppMain;
typedef struct _AppMainAppMainClass AppMainAppMainClass;
typedef struct _AppMainAppMainPrivate AppMainAppMainPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _AppMainAppMain {
	BootstrapingprojectFactoriesAbstractMain parent_instance;
	AppMainAppMainPrivate * priv;
};

struct _AppMainAppMainClass {
	BootstrapingprojectFactoriesAbstractMainClass parent_class;
};


static gpointer app_main_app_main_parent_class = NULL;

GType app_main_app_main_get_type (void) G_GNUC_CONST;
enum  {
	APP_MAIN_APP_MAIN_DUMMY_PROPERTY
};
gint app_main_app_main_main (gchar** args, int args_length1);
AppMainAppMain* app_main_app_main_new (void);
AppMainAppMain* app_main_app_main_construct (GType object_type);


gint app_main_app_main_main (gchar** args, int args_length1) {
	gint result = 0;
	AppMainAppMain* _tmp0_;
	AppMainAppMain* main_class;
	gint _tmp1_ = 0;
#line 26 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/src/AppMain.vala"
	_tmp0_ = app_main_app_main_new ();
#line 26 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/src/AppMain.vala"
	main_class = _tmp0_;
#line 27 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/src/AppMain.vala"
	bootstrapingproject_factories_factory_init ((BootstrapingprojectFactoriesAbstractMain*) main_class);
#line 28 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/src/AppMain.vala"
	_tmp1_ = bootstrapingproject_factories_abstract_main_run ((BootstrapingprojectFactoriesAbstractMain*) main_class, &args, &args_length1);
#line 28 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/src/AppMain.vala"
	result = _tmp1_;
#line 28 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/src/AppMain.vala"
	_g_object_unref0 (main_class);
#line 28 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/src/AppMain.vala"
	return result;
#line 83 "AppMain.c"
}


int main (int argc, char ** argv) {
#line 24 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/src/AppMain.vala"
	g_type_init ();
#line 24 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/src/AppMain.vala"
	return app_main_app_main_main (argv, argc);
#line 92 "AppMain.c"
}


AppMainAppMain* app_main_app_main_construct (GType object_type) {
	AppMainAppMain * self = NULL;
	gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
#line 31 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/src/AppMain.vala"
	self = (AppMainAppMain*) bootstrapingproject_factories_abstract_main_construct (object_type);
#line 33 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/src/AppMain.vala"
	_tmp0_ = g_strdup (PKGDATADIR);
#line 33 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/src/AppMain.vala"
	_g_free0 (((BootstrapingprojectFactoriesAbstractMain*) self)->build_pkg_data_dir);
#line 33 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/src/AppMain.vala"
	((BootstrapingprojectFactoriesAbstractMain*) self)->build_pkg_data_dir = _tmp0_;
#line 35 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/src/AppMain.vala"
	_tmp1_ = g_strdup ("Bootstrapingproject");
#line 35 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/src/AppMain.vala"
	_g_free0 (((BootstrapingprojectFactoriesAbstractMain*) self)->program_name);
#line 35 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/src/AppMain.vala"
	((BootstrapingprojectFactoriesAbstractMain*) self)->program_name = _tmp1_;
#line 36 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/src/AppMain.vala"
	_tmp2_ = g_strdup ("bootstrapingproject");
#line 36 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/src/AppMain.vala"
	_g_free0 (((BootstrapingprojectFactoriesAbstractMain*) self)->exec_name);
#line 36 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/src/AppMain.vala"
	((BootstrapingprojectFactoriesAbstractMain*) self)->exec_name = _tmp2_;
#line 31 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/src/AppMain.vala"
	return self;
#line 123 "AppMain.c"
}


AppMainAppMain* app_main_app_main_new (void) {
#line 31 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/src/AppMain.vala"
	return app_main_app_main_construct (APP_MAIN_TYPE_APP_MAIN);
#line 130 "AppMain.c"
}


static void app_main_app_main_class_init (AppMainAppMainClass * klass) {
#line 22 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/src/AppMain.vala"
	app_main_app_main_parent_class = g_type_class_peek_parent (klass);
#line 137 "AppMain.c"
}


static void app_main_app_main_instance_init (AppMainAppMain * self) {
}


GType app_main_app_main_get_type (void) {
	static volatile gsize app_main_app_main_type_id__volatile = 0;
	if (g_once_init_enter (&app_main_app_main_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (AppMainAppMainClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) app_main_app_main_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AppMainAppMain), 0, (GInstanceInitFunc) app_main_app_main_instance_init, NULL };
		GType app_main_app_main_type_id;
		app_main_app_main_type_id = g_type_register_static (BOOTSTRAPINGPROJECT_FACTORIES_TYPE_ABSTRACT_MAIN, "AppMainAppMain", &g_define_type_info, 0);
		g_once_init_leave (&app_main_app_main_type_id__volatile, app_main_app_main_type_id);
	}
	return app_main_app_main_type_id__volatile;
}



