/* Paths.c generated by valac 0.20.1, the Vala compiler
 * generated from Paths.vala, do not modify */

/**/
/*  Copyright (C) 2011 Gwenaël Pluchon*/
/**/
/*  This program is free software: you can redistribute it and/or modify*/
/*  it under the terms of the GNU General Public License as published by*/
/*  the Free Software Foundation, either version 3 of the License, or*/
/*  (at your option) any later version.*/
/**/
/*  This program is distributed in the hope that it will be useful,*/
/*  but WITHOUT ANY WARRANTY; without even the implied warranty of*/
/*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the*/
/*  GNU General Public License for more details.*/
/**/
/*  You should have received a copy of the GNU General Public License*/
/*  along with this program.  If not, see <http://www.gnu.org/licenses/>.*/
/**/

#include <glib.h>
#include <glib-object.h>
#include <gio/gio.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>


#define BOOTSTRAPINGPROJECT_SYSTEM_TYPE_PATHS (bootstrapingproject_system_paths_get_type ())
#define BOOTSTRAPINGPROJECT_SYSTEM_PATHS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOOTSTRAPINGPROJECT_SYSTEM_TYPE_PATHS, BootstrapingprojectSystemPaths))
#define BOOTSTRAPINGPROJECT_SYSTEM_PATHS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOOTSTRAPINGPROJECT_SYSTEM_TYPE_PATHS, BootstrapingprojectSystemPathsClass))
#define BOOTSTRAPINGPROJECT_SYSTEM_IS_PATHS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOOTSTRAPINGPROJECT_SYSTEM_TYPE_PATHS))
#define BOOTSTRAPINGPROJECT_SYSTEM_IS_PATHS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOOTSTRAPINGPROJECT_SYSTEM_TYPE_PATHS))
#define BOOTSTRAPINGPROJECT_SYSTEM_PATHS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOOTSTRAPINGPROJECT_SYSTEM_TYPE_PATHS, BootstrapingprojectSystemPathsClass))

typedef struct _BootstrapingprojectSystemPaths BootstrapingprojectSystemPaths;
typedef struct _BootstrapingprojectSystemPathsClass BootstrapingprojectSystemPathsClass;
typedef struct _BootstrapingprojectSystemPathsPrivate BootstrapingprojectSystemPathsPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _BootstrapingprojectSystemPaths {
	GObject parent_instance;
	BootstrapingprojectSystemPathsPrivate * priv;
};

struct _BootstrapingprojectSystemPathsClass {
	GObjectClass parent_class;
};


static gpointer bootstrapingproject_system_paths_parent_class = NULL;
static GFile* bootstrapingproject_system_paths__HomeFolder;
static GFile* bootstrapingproject_system_paths__HomeFolder = NULL;
static GFile* bootstrapingproject_system_paths__DataFolder;
static GFile* bootstrapingproject_system_paths__DataFolder = NULL;
static GFile* bootstrapingproject_system_paths__ThemeFolder;
static GFile* bootstrapingproject_system_paths__ThemeFolder = NULL;
static GFile* bootstrapingproject_system_paths__ConfigHomeFolder;
static GFile* bootstrapingproject_system_paths__ConfigHomeFolder = NULL;
static GFile* bootstrapingproject_system_paths__DataHomeFolder;
static GFile* bootstrapingproject_system_paths__DataHomeFolder = NULL;
static GFile* bootstrapingproject_system_paths__CacheHomeFolder;
static GFile* bootstrapingproject_system_paths__CacheHomeFolder = NULL;
static GeeArrayList* bootstrapingproject_system_paths__DataDirFolders;
static GeeArrayList* bootstrapingproject_system_paths__DataDirFolders = NULL;
static GFile* bootstrapingproject_system_paths__AppConfigFolder;
static GFile* bootstrapingproject_system_paths__AppConfigFolder = NULL;
static GFile* bootstrapingproject_system_paths__AppDataFolder;
static GFile* bootstrapingproject_system_paths__AppDataFolder = NULL;
static GFile* bootstrapingproject_system_paths__AppThemeFolder;
static GFile* bootstrapingproject_system_paths__AppThemeFolder = NULL;
static GFile* bootstrapingproject_system_paths__AppCacheFolder;
static GFile* bootstrapingproject_system_paths__AppCacheFolder = NULL;

GType bootstrapingproject_system_paths_get_type (void) G_GNUC_CONST;
enum  {
	BOOTSTRAPINGPROJECT_SYSTEM_PATHS_DUMMY_PROPERTY
};
static BootstrapingprojectSystemPaths* bootstrapingproject_system_paths_new (void);
static BootstrapingprojectSystemPaths* bootstrapingproject_system_paths_construct (GType object_type);
void bootstrapingproject_system_paths_initialize (const gchar* app_name, const gchar* data_folder);
GFile* bootstrapingproject_system_paths_get_HomeFolder (void);
void bootstrapingproject_system_paths_set_HomeFolder (GFile* value);
GFile* bootstrapingproject_system_paths_get_DataFolder (void);
void bootstrapingproject_system_paths_set_DataFolder (GFile* value);
GFile* bootstrapingproject_system_paths_get_ThemeFolder (void);
void bootstrapingproject_system_paths_set_ThemeFolder (GFile* value);
GFile* bootstrapingproject_system_paths_get_ConfigHomeFolder (void);
void bootstrapingproject_system_paths_set_ConfigHomeFolder (GFile* value);
GFile* bootstrapingproject_system_paths_get_DataHomeFolder (void);
void bootstrapingproject_system_paths_set_DataHomeFolder (GFile* value);
GFile* bootstrapingproject_system_paths_get_CacheHomeFolder (void);
void bootstrapingproject_system_paths_set_CacheHomeFolder (GFile* value);
GeeArrayList* bootstrapingproject_system_paths_get_DataDirFolders (void);
void bootstrapingproject_system_paths_set_DataDirFolders (GeeArrayList* value);
GFile* bootstrapingproject_system_paths_get_AppConfigFolder (void);
void bootstrapingproject_system_paths_set_AppConfigFolder (GFile* value);
GFile* bootstrapingproject_system_paths_get_AppDataFolder (void);
void bootstrapingproject_system_paths_set_AppDataFolder (GFile* value);
GFile* bootstrapingproject_system_paths_get_AppThemeFolder (void);
void bootstrapingproject_system_paths_set_AppThemeFolder (GFile* value);
GFile* bootstrapingproject_system_paths_get_AppCacheFolder (void);
void bootstrapingproject_system_paths_set_AppCacheFolder (GFile* value);
gboolean bootstrapingproject_system_paths_ensure_directory_exists (GFile* dir);
static void bootstrapingproject_system_paths_finalize (GObject* obj);
static void _vala_bootstrapingproject_system_paths_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_bootstrapingproject_system_paths_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static gint _vala_array_length (gpointer array);


static BootstrapingprojectSystemPaths* bootstrapingproject_system_paths_construct (GType object_type) {
	BootstrapingprojectSystemPaths * self = NULL;
#line 90 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	self = (BootstrapingprojectSystemPaths*) g_object_new (object_type, NULL);
#line 90 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	return self;
#line 120 "Paths.c"
}


static BootstrapingprojectSystemPaths* bootstrapingproject_system_paths_new (void) {
#line 90 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	return bootstrapingproject_system_paths_construct (BOOTSTRAPINGPROJECT_SYSTEM_TYPE_PATHS);
#line 127 "Paths.c"
}


/**
 * Initialize the class, creating the {@link GLib.File} instances for all
 * common paths.  Also ensure that any writable directory exists.
 *
 * @param app_name the name of the application
 * @param data_folder the path to the application's data folder
 */
void bootstrapingproject_system_paths_initialize (const gchar* app_name, const gchar* data_folder) {
	GFile* _tmp0_;
	GFile* _tmp1_;
	const gchar* _tmp2_ = NULL;
	GFile* _tmp3_ = NULL;
	GFile* _tmp4_;
	GFile* _tmp5_;
	GFile* _tmp6_;
	const gchar* _tmp7_;
	GFile* _tmp8_ = NULL;
	GFile* _tmp9_;
	GFile* _tmp10_;
	GFile* _tmp11_;
	GFile* _tmp12_;
	GFile* _tmp13_;
	GFile* _tmp14_ = NULL;
	GFile* _tmp15_;
	GFile* _tmp16_;
	GFile* _tmp17_;
	const gchar* _tmp18_ = NULL;
	GFile* _tmp19_ = NULL;
	GFile* _tmp20_;
	GFile* _tmp21_;
	GFile* _tmp22_;
	const gchar* _tmp23_ = NULL;
	GFile* _tmp24_ = NULL;
	GFile* _tmp25_;
	GFile* _tmp26_;
	GFile* _tmp27_;
	const gchar* _tmp28_ = NULL;
	GFile* _tmp29_ = NULL;
	GFile* _tmp30_;
	GeeArrayList* _tmp31_;
	GeeArrayList* dirs;
	gchar** _tmp32_;
	gchar** _tmp33_ = NULL;
	GeeArrayList* _tmp39_;
	GeeArrayList* _tmp40_;
	GeeArrayList* _tmp41_;
	GFile* _tmp42_;
	GFile* _tmp43_;
	GFile* _tmp44_;
	GFile* _tmp45_;
	const gchar* _tmp46_;
	GFile* _tmp47_ = NULL;
	GFile* _tmp48_;
	GFile* _tmp49_;
	GFile* _tmp50_;
	GFile* _tmp51_;
	GFile* _tmp52_;
	const gchar* _tmp53_;
	GFile* _tmp54_ = NULL;
	GFile* _tmp55_;
	GFile* _tmp56_;
	GFile* _tmp57_;
	GFile* _tmp58_;
	GFile* _tmp59_;
	GFile* _tmp60_ = NULL;
	GFile* _tmp61_;
	GFile* _tmp62_;
	GFile* _tmp63_;
	GFile* _tmp64_;
	GFile* _tmp65_;
	const gchar* _tmp66_;
	GFile* _tmp67_ = NULL;
	GFile* _tmp68_;
	GFile* _tmp69_;
	GFile* _tmp70_;
	GFile* _tmp71_;
	GFile* _tmp72_;
	GFile* _tmp73_;
	GFile* _tmp74_;
	GFile* _tmp75_;
	GFile* _tmp76_;
#line 101 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	g_return_if_fail (app_name != NULL);
#line 101 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	g_return_if_fail (data_folder != NULL);
#line 104 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp0_ = bootstrapingproject_system_paths_get_HomeFolder ();
#line 104 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp1_ = _tmp0_;
#line 104 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp2_ = g_get_home_dir ();
#line 104 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp3_ = g_file_new_for_path (_tmp2_);
#line 104 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp4_ = _tmp3_;
#line 104 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	bootstrapingproject_system_paths_set_HomeFolder (_tmp4_);
#line 104 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_g_object_unref0 (_tmp4_);
#line 105 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp5_ = bootstrapingproject_system_paths_get_DataFolder ();
#line 105 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp6_ = _tmp5_;
#line 105 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp7_ = data_folder;
#line 105 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp8_ = g_file_new_for_path (_tmp7_);
#line 105 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp9_ = _tmp8_;
#line 105 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	bootstrapingproject_system_paths_set_DataFolder (_tmp9_);
#line 105 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_g_object_unref0 (_tmp9_);
#line 106 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp10_ = bootstrapingproject_system_paths_get_ThemeFolder ();
#line 106 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp11_ = _tmp10_;
#line 106 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp12_ = bootstrapingproject_system_paths_get_DataFolder ();
#line 106 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp13_ = _tmp12_;
#line 106 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp14_ = g_file_get_child (_tmp13_, "themes");
#line 106 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp15_ = _tmp14_;
#line 106 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	bootstrapingproject_system_paths_set_ThemeFolder (_tmp15_);
#line 106 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_g_object_unref0 (_tmp15_);
#line 110 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp16_ = bootstrapingproject_system_paths_get_ConfigHomeFolder ();
#line 110 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp17_ = _tmp16_;
#line 110 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp18_ = g_get_user_config_dir ();
#line 110 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp19_ = g_file_new_for_path (_tmp18_);
#line 110 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp20_ = _tmp19_;
#line 110 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	bootstrapingproject_system_paths_set_ConfigHomeFolder (_tmp20_);
#line 110 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_g_object_unref0 (_tmp20_);
#line 111 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp21_ = bootstrapingproject_system_paths_get_DataHomeFolder ();
#line 111 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp22_ = _tmp21_;
#line 111 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp23_ = g_get_user_data_dir ();
#line 111 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp24_ = g_file_new_for_path (_tmp23_);
#line 111 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp25_ = _tmp24_;
#line 111 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	bootstrapingproject_system_paths_set_DataHomeFolder (_tmp25_);
#line 111 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_g_object_unref0 (_tmp25_);
#line 112 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp26_ = bootstrapingproject_system_paths_get_CacheHomeFolder ();
#line 112 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp27_ = _tmp26_;
#line 112 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp28_ = g_get_user_cache_dir ();
#line 112 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp29_ = g_file_new_for_path (_tmp28_);
#line 112 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp30_ = _tmp29_;
#line 112 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	bootstrapingproject_system_paths_set_CacheHomeFolder (_tmp30_);
#line 112 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_g_object_unref0 (_tmp30_);
#line 114 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp31_ = gee_array_list_new (G_TYPE_FILE, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL);
#line 114 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	dirs = _tmp31_;
#line 115 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp33_ = _tmp32_ = g_get_system_data_dirs ();
#line 308 "Paths.c"
	{
		gchar** path_collection = NULL;
		gint path_collection_length1 = 0;
		gint _path_collection_size_ = 0;
		gint path_it = 0;
#line 115 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
		path_collection = _tmp33_;
#line 115 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
		path_collection_length1 = _vala_array_length (_tmp32_);
#line 115 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
		for (path_it = 0; path_it < _vala_array_length (_tmp32_); path_it = path_it + 1) {
#line 320 "Paths.c"
			gchar* _tmp34_;
			gchar* path = NULL;
#line 115 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
			_tmp34_ = g_strdup (path_collection[path_it]);
#line 115 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
			path = _tmp34_;
#line 327 "Paths.c"
			{
				GeeArrayList* _tmp35_;
				const gchar* _tmp36_;
				GFile* _tmp37_ = NULL;
				GFile* _tmp38_;
#line 116 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
				_tmp35_ = dirs;
#line 116 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
				_tmp36_ = path;
#line 116 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
				_tmp37_ = g_file_new_for_path (_tmp36_);
#line 116 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
				_tmp38_ = _tmp37_;
#line 116 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
				gee_abstract_collection_add ((GeeAbstractCollection*) _tmp35_, _tmp38_);
#line 116 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
				_g_object_unref0 (_tmp38_);
#line 115 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
				_g_free0 (path);
#line 347 "Paths.c"
			}
		}
	}
#line 117 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp39_ = bootstrapingproject_system_paths_get_DataDirFolders ();
#line 117 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp40_ = _tmp39_;
#line 117 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp41_ = dirs;
#line 117 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	bootstrapingproject_system_paths_set_DataDirFolders (_tmp41_);
#line 121 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp42_ = bootstrapingproject_system_paths_get_AppConfigFolder ();
#line 121 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp43_ = _tmp42_;
#line 121 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp44_ = bootstrapingproject_system_paths_get_ConfigHomeFolder ();
#line 121 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp45_ = _tmp44_;
#line 121 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp46_ = app_name;
#line 121 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp47_ = g_file_get_child (_tmp45_, _tmp46_);
#line 121 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp48_ = _tmp47_;
#line 121 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	bootstrapingproject_system_paths_set_AppConfigFolder (_tmp48_);
#line 121 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_g_object_unref0 (_tmp48_);
#line 122 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp49_ = bootstrapingproject_system_paths_get_AppDataFolder ();
#line 122 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp50_ = _tmp49_;
#line 122 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp51_ = bootstrapingproject_system_paths_get_DataHomeFolder ();
#line 122 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp52_ = _tmp51_;
#line 122 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp53_ = app_name;
#line 122 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp54_ = g_file_get_child (_tmp52_, _tmp53_);
#line 122 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp55_ = _tmp54_;
#line 122 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	bootstrapingproject_system_paths_set_AppDataFolder (_tmp55_);
#line 122 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_g_object_unref0 (_tmp55_);
#line 123 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp56_ = bootstrapingproject_system_paths_get_AppThemeFolder ();
#line 123 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp57_ = _tmp56_;
#line 123 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp58_ = bootstrapingproject_system_paths_get_AppDataFolder ();
#line 123 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp59_ = _tmp58_;
#line 123 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp60_ = g_file_get_child (_tmp59_, "themes");
#line 123 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp61_ = _tmp60_;
#line 123 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	bootstrapingproject_system_paths_set_AppThemeFolder (_tmp61_);
#line 123 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_g_object_unref0 (_tmp61_);
#line 124 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp62_ = bootstrapingproject_system_paths_get_AppCacheFolder ();
#line 124 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp63_ = _tmp62_;
#line 124 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp64_ = bootstrapingproject_system_paths_get_CacheHomeFolder ();
#line 124 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp65_ = _tmp64_;
#line 124 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp66_ = app_name;
#line 124 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp67_ = g_file_get_child (_tmp65_, _tmp66_);
#line 124 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp68_ = _tmp67_;
#line 124 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	bootstrapingproject_system_paths_set_AppCacheFolder (_tmp68_);
#line 124 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_g_object_unref0 (_tmp68_);
#line 128 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp69_ = bootstrapingproject_system_paths_get_AppConfigFolder ();
#line 128 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp70_ = _tmp69_;
#line 128 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	bootstrapingproject_system_paths_ensure_directory_exists (_tmp70_);
#line 129 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp71_ = bootstrapingproject_system_paths_get_AppDataFolder ();
#line 129 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp72_ = _tmp71_;
#line 129 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	bootstrapingproject_system_paths_ensure_directory_exists (_tmp72_);
#line 130 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp73_ = bootstrapingproject_system_paths_get_AppThemeFolder ();
#line 130 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp74_ = _tmp73_;
#line 130 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	bootstrapingproject_system_paths_ensure_directory_exists (_tmp74_);
#line 131 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp75_ = bootstrapingproject_system_paths_get_AppCacheFolder ();
#line 131 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp76_ = _tmp75_;
#line 131 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	bootstrapingproject_system_paths_ensure_directory_exists (_tmp76_);
#line 101 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_g_object_unref0 (dirs);
#line 455 "Paths.c"
}


/**
 * Creates the directory if it does not already exist
 *
 * @param dir the directory to ensure exists
 * @return true if a directory was created, false otherwise
 */
gboolean bootstrapingproject_system_paths_ensure_directory_exists (GFile* dir) {
	gboolean result = FALSE;
	GFile* _tmp0_;
	gboolean _tmp1_ = FALSE;
	GError * _inner_error_ = NULL;
#line 140 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	g_return_val_if_fail (dir != NULL, FALSE);
#line 142 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp0_ = dir;
#line 142 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp1_ = g_file_query_exists (_tmp0_, NULL);
#line 142 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	if (!_tmp1_) {
#line 478 "Paths.c"
		{
			GFile* _tmp2_;
#line 144 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
			_tmp2_ = dir;
#line 144 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
			g_file_make_directory_with_parents (_tmp2_, NULL, &_inner_error_);
#line 144 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
			if (_inner_error_ != NULL) {
#line 487 "Paths.c"
				goto __catch2_g_error;
			}
#line 145 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
			result = TRUE;
#line 145 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
			return result;
#line 494 "Paths.c"
		}
		goto __finally2;
		__catch2_g_error:
		{
			GError* e = NULL;
			GFile* _tmp3_;
			gchar* _tmp4_ = NULL;
			gchar* _tmp5_;
			const gchar* _tmp6_;
			const gchar* _tmp8_;
			GError* _tmp9_;
			const gchar* _tmp10_;
#line 143 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
			e = _inner_error_;
#line 143 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
			_inner_error_ = NULL;
#line 147 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
			_tmp3_ = dir;
#line 147 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
			_tmp4_ = g_file_get_path (_tmp3_);
#line 147 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
			_tmp5_ = _tmp4_;
#line 147 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
			_tmp6_ = _tmp5_;
#line 147 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
			if (_tmp6_ == NULL) {
#line 521 "Paths.c"
				gchar* _tmp7_;
#line 147 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
				_tmp7_ = g_strdup ("");
#line 147 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
				_g_free0 (_tmp5_);
#line 147 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
				_tmp5_ = _tmp7_;
#line 529 "Paths.c"
			}
#line 147 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
			_tmp8_ = _tmp5_;
#line 147 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
			_tmp9_ = e;
#line 147 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
			_tmp10_ = _tmp9_->message;
#line 147 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
			g_error ("Paths.vala:147: Could not access or create the directory '%s'. (%s)", _tmp8_, _tmp10_);
#line 143 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
			_g_free0 (_tmp5_);
#line 143 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
			_g_error_free0 (e);
#line 543 "Paths.c"
		}
		__finally2:
#line 143 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 143 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
		g_clear_error (&_inner_error_);
#line 143 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
		return FALSE;
#line 552 "Paths.c"
	}
#line 150 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	result = FALSE;
#line 150 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	return result;
#line 558 "Paths.c"
}


GFile* bootstrapingproject_system_paths_get_HomeFolder (void) {
	GFile* result;
	GFile* _tmp0_;
#line 35 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp0_ = bootstrapingproject_system_paths__HomeFolder;
#line 35 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	result = _tmp0_;
#line 35 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	return result;
#line 571 "Paths.c"
}


static gpointer _g_object_ref0 (gpointer self) {
#line 35 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	return self ? g_object_ref (self) : NULL;
#line 578 "Paths.c"
}


void bootstrapingproject_system_paths_set_HomeFolder (GFile* value) {
	GFile* _tmp0_;
	GFile* _tmp1_;
#line 35 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp0_ = value;
#line 35 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 35 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_g_object_unref0 (bootstrapingproject_system_paths__HomeFolder);
#line 35 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	bootstrapingproject_system_paths__HomeFolder = _tmp1_;
#line 593 "Paths.c"
}


GFile* bootstrapingproject_system_paths_get_DataFolder (void) {
	GFile* result;
	GFile* _tmp0_;
#line 41 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp0_ = bootstrapingproject_system_paths__DataFolder;
#line 41 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	result = _tmp0_;
#line 41 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	return result;
#line 606 "Paths.c"
}


void bootstrapingproject_system_paths_set_DataFolder (GFile* value) {
	GFile* _tmp0_;
	GFile* _tmp1_;
#line 41 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp0_ = value;
#line 41 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 41 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_g_object_unref0 (bootstrapingproject_system_paths__DataFolder);
#line 41 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	bootstrapingproject_system_paths__DataFolder = _tmp1_;
#line 621 "Paths.c"
}


GFile* bootstrapingproject_system_paths_get_ThemeFolder (void) {
	GFile* result;
	GFile* _tmp0_;
#line 46 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp0_ = bootstrapingproject_system_paths__ThemeFolder;
#line 46 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	result = _tmp0_;
#line 46 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	return result;
#line 634 "Paths.c"
}


void bootstrapingproject_system_paths_set_ThemeFolder (GFile* value) {
	GFile* _tmp0_;
	GFile* _tmp1_;
#line 46 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp0_ = value;
#line 46 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 46 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_g_object_unref0 (bootstrapingproject_system_paths__ThemeFolder);
#line 46 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	bootstrapingproject_system_paths__ThemeFolder = _tmp1_;
#line 649 "Paths.c"
}


GFile* bootstrapingproject_system_paths_get_ConfigHomeFolder (void) {
	GFile* result;
	GFile* _tmp0_;
#line 51 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp0_ = bootstrapingproject_system_paths__ConfigHomeFolder;
#line 51 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	result = _tmp0_;
#line 51 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	return result;
#line 662 "Paths.c"
}


void bootstrapingproject_system_paths_set_ConfigHomeFolder (GFile* value) {
	GFile* _tmp0_;
	GFile* _tmp1_;
#line 51 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp0_ = value;
#line 51 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 51 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_g_object_unref0 (bootstrapingproject_system_paths__ConfigHomeFolder);
#line 51 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	bootstrapingproject_system_paths__ConfigHomeFolder = _tmp1_;
#line 677 "Paths.c"
}


GFile* bootstrapingproject_system_paths_get_DataHomeFolder (void) {
	GFile* result;
	GFile* _tmp0_;
#line 56 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp0_ = bootstrapingproject_system_paths__DataHomeFolder;
#line 56 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	result = _tmp0_;
#line 56 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	return result;
#line 690 "Paths.c"
}


void bootstrapingproject_system_paths_set_DataHomeFolder (GFile* value) {
	GFile* _tmp0_;
	GFile* _tmp1_;
#line 56 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp0_ = value;
#line 56 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 56 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_g_object_unref0 (bootstrapingproject_system_paths__DataHomeFolder);
#line 56 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	bootstrapingproject_system_paths__DataHomeFolder = _tmp1_;
#line 705 "Paths.c"
}


GFile* bootstrapingproject_system_paths_get_CacheHomeFolder (void) {
	GFile* result;
	GFile* _tmp0_;
#line 61 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp0_ = bootstrapingproject_system_paths__CacheHomeFolder;
#line 61 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	result = _tmp0_;
#line 61 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	return result;
#line 718 "Paths.c"
}


void bootstrapingproject_system_paths_set_CacheHomeFolder (GFile* value) {
	GFile* _tmp0_;
	GFile* _tmp1_;
#line 61 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp0_ = value;
#line 61 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 61 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_g_object_unref0 (bootstrapingproject_system_paths__CacheHomeFolder);
#line 61 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	bootstrapingproject_system_paths__CacheHomeFolder = _tmp1_;
#line 733 "Paths.c"
}


GeeArrayList* bootstrapingproject_system_paths_get_DataDirFolders (void) {
	GeeArrayList* result;
	GeeArrayList* _tmp0_;
#line 66 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp0_ = bootstrapingproject_system_paths__DataDirFolders;
#line 66 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	result = _tmp0_;
#line 66 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	return result;
#line 746 "Paths.c"
}


void bootstrapingproject_system_paths_set_DataDirFolders (GeeArrayList* value) {
	GeeArrayList* _tmp0_;
	GeeArrayList* _tmp1_;
#line 66 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp0_ = value;
#line 66 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 66 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_g_object_unref0 (bootstrapingproject_system_paths__DataDirFolders);
#line 66 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	bootstrapingproject_system_paths__DataDirFolders = _tmp1_;
#line 761 "Paths.c"
}


GFile* bootstrapingproject_system_paths_get_AppConfigFolder (void) {
	GFile* result;
	GFile* _tmp0_;
#line 72 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp0_ = bootstrapingproject_system_paths__AppConfigFolder;
#line 72 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	result = _tmp0_;
#line 72 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	return result;
#line 774 "Paths.c"
}


void bootstrapingproject_system_paths_set_AppConfigFolder (GFile* value) {
	GFile* _tmp0_;
	GFile* _tmp1_;
#line 72 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp0_ = value;
#line 72 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 72 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_g_object_unref0 (bootstrapingproject_system_paths__AppConfigFolder);
#line 72 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	bootstrapingproject_system_paths__AppConfigFolder = _tmp1_;
#line 789 "Paths.c"
}


GFile* bootstrapingproject_system_paths_get_AppDataFolder (void) {
	GFile* result;
	GFile* _tmp0_;
#line 77 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp0_ = bootstrapingproject_system_paths__AppDataFolder;
#line 77 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	result = _tmp0_;
#line 77 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	return result;
#line 802 "Paths.c"
}


void bootstrapingproject_system_paths_set_AppDataFolder (GFile* value) {
	GFile* _tmp0_;
	GFile* _tmp1_;
#line 77 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp0_ = value;
#line 77 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 77 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_g_object_unref0 (bootstrapingproject_system_paths__AppDataFolder);
#line 77 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	bootstrapingproject_system_paths__AppDataFolder = _tmp1_;
#line 817 "Paths.c"
}


GFile* bootstrapingproject_system_paths_get_AppThemeFolder (void) {
	GFile* result;
	GFile* _tmp0_;
#line 82 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp0_ = bootstrapingproject_system_paths__AppThemeFolder;
#line 82 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	result = _tmp0_;
#line 82 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	return result;
#line 830 "Paths.c"
}


void bootstrapingproject_system_paths_set_AppThemeFolder (GFile* value) {
	GFile* _tmp0_;
	GFile* _tmp1_;
#line 82 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp0_ = value;
#line 82 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 82 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_g_object_unref0 (bootstrapingproject_system_paths__AppThemeFolder);
#line 82 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	bootstrapingproject_system_paths__AppThemeFolder = _tmp1_;
#line 845 "Paths.c"
}


GFile* bootstrapingproject_system_paths_get_AppCacheFolder (void) {
	GFile* result;
	GFile* _tmp0_;
#line 87 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp0_ = bootstrapingproject_system_paths__AppCacheFolder;
#line 87 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	result = _tmp0_;
#line 87 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	return result;
#line 858 "Paths.c"
}


void bootstrapingproject_system_paths_set_AppCacheFolder (GFile* value) {
	GFile* _tmp0_;
	GFile* _tmp1_;
#line 87 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp0_ = value;
#line 87 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_tmp1_ = _g_object_ref0 (_tmp0_);
#line 87 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	_g_object_unref0 (bootstrapingproject_system_paths__AppCacheFolder);
#line 87 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	bootstrapingproject_system_paths__AppCacheFolder = _tmp1_;
#line 873 "Paths.c"
}


static void bootstrapingproject_system_paths_class_init (BootstrapingprojectSystemPathsClass * klass) {
#line 30 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	bootstrapingproject_system_paths_parent_class = g_type_class_peek_parent (klass);
#line 30 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_bootstrapingproject_system_paths_get_property;
#line 30 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_bootstrapingproject_system_paths_set_property;
#line 30 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	G_OBJECT_CLASS (klass)->finalize = bootstrapingproject_system_paths_finalize;
#line 886 "Paths.c"
}


static void bootstrapingproject_system_paths_instance_init (BootstrapingprojectSystemPaths * self) {
}


static void bootstrapingproject_system_paths_finalize (GObject* obj) {
	BootstrapingprojectSystemPaths * self;
#line 30 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, BOOTSTRAPINGPROJECT_SYSTEM_TYPE_PATHS, BootstrapingprojectSystemPaths);
#line 30 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	G_OBJECT_CLASS (bootstrapingproject_system_paths_parent_class)->finalize (obj);
#line 900 "Paths.c"
}


/**
 * A wrapper class that gives static instances of {@link GLib.File}
 * for commonly used paths.  Most paths are retrieved from
 * {@link GLib.Environment}, which on Linux uses the XDG Base Directory
 * specification (see [[http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html]]).
 *
 * Initializing this class also ensures any writable directories exist.
 */
GType bootstrapingproject_system_paths_get_type (void) {
	static volatile gsize bootstrapingproject_system_paths_type_id__volatile = 0;
	if (g_once_init_enter (&bootstrapingproject_system_paths_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (BootstrapingprojectSystemPathsClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) bootstrapingproject_system_paths_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (BootstrapingprojectSystemPaths), 0, (GInstanceInitFunc) bootstrapingproject_system_paths_instance_init, NULL };
		GType bootstrapingproject_system_paths_type_id;
		bootstrapingproject_system_paths_type_id = g_type_register_static (G_TYPE_OBJECT, "BootstrapingprojectSystemPaths", &g_define_type_info, 0);
		g_once_init_leave (&bootstrapingproject_system_paths_type_id__volatile, bootstrapingproject_system_paths_type_id);
	}
	return bootstrapingproject_system_paths_type_id__volatile;
}


static void _vala_bootstrapingproject_system_paths_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	BootstrapingprojectSystemPaths * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, BOOTSTRAPINGPROJECT_SYSTEM_TYPE_PATHS, BootstrapingprojectSystemPaths);
#line 30 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	switch (property_id) {
#line 929 "Paths.c"
		default:
#line 30 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 30 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
		break;
#line 935 "Paths.c"
	}
}


static void _vala_bootstrapingproject_system_paths_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	BootstrapingprojectSystemPaths * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, BOOTSTRAPINGPROJECT_SYSTEM_TYPE_PATHS, BootstrapingprojectSystemPaths);
#line 30 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
	switch (property_id) {
#line 945 "Paths.c"
		default:
#line 30 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 30 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/System/Paths.vala"
		break;
#line 951 "Paths.c"
	}
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



