/* bootstrapingproject-internal.h generated by valac 0.20.1, the Vala compiler, do not modify */


#ifndef __BOOTSTRAPINGPROJECT_INTERNAL_H__
#define __BOOTSTRAPINGPROJECT_INTERNAL_H__


G_BEGIN_DECLS





G_END_DECLS

#endif
