/* MainController.c generated by valac 0.20.1, the Vala compiler
 * generated from MainController.vala, do not modify */

/**/
/*  Copyright (C) 2011 Gwenaël Pluchon*/
/**/
/*  This program is free software: you can redistribute it and/or modify*/
/*  it under the terms of the GNU General Public License as published by*/
/*  the Free Software Foundation, either version 3 of the License, or*/
/*  (at your option) any later version.*/
/**/
/*  This program is distributed in the hope that it will be useful,*/
/*  but WITHOUT ANY WARRANTY; without even the implied warranty of*/
/*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the*/
/*  GNU General Public License for more details.*/
/**/
/*  You should have received a copy of the GNU General Public License*/
/*  along with this program.  If not, see <http://www.gnu.org/licenses/>.*/
/**/

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>


#define BOOTSTRAPINGPROJECT_TYPE_MAIN_CONTROLLER (bootstrapingproject_main_controller_get_type ())
#define BOOTSTRAPINGPROJECT_MAIN_CONTROLLER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOOTSTRAPINGPROJECT_TYPE_MAIN_CONTROLLER, BootstrapingprojectMainController))
#define BOOTSTRAPINGPROJECT_MAIN_CONTROLLER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOOTSTRAPINGPROJECT_TYPE_MAIN_CONTROLLER, BootstrapingprojectMainControllerClass))
#define BOOTSTRAPINGPROJECT_IS_MAIN_CONTROLLER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOOTSTRAPINGPROJECT_TYPE_MAIN_CONTROLLER))
#define BOOTSTRAPINGPROJECT_IS_MAIN_CONTROLLER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOOTSTRAPINGPROJECT_TYPE_MAIN_CONTROLLER))
#define BOOTSTRAPINGPROJECT_MAIN_CONTROLLER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOOTSTRAPINGPROJECT_TYPE_MAIN_CONTROLLER, BootstrapingprojectMainControllerClass))

typedef struct _BootstrapingprojectMainController BootstrapingprojectMainController;
typedef struct _BootstrapingprojectMainControllerClass BootstrapingprojectMainControllerClass;
typedef struct _BootstrapingprojectMainControllerPrivate BootstrapingprojectMainControllerPrivate;

#define BOOTSTRAPINGPROJECT_WIDGETS_TYPE_MAIN_WINDOW (bootstrapingproject_widgets_main_window_get_type ())
#define BOOTSTRAPINGPROJECT_WIDGETS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOOTSTRAPINGPROJECT_WIDGETS_TYPE_MAIN_WINDOW, BootstrapingprojectWidgetsMainWindow))
#define BOOTSTRAPINGPROJECT_WIDGETS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOOTSTRAPINGPROJECT_WIDGETS_TYPE_MAIN_WINDOW, BootstrapingprojectWidgetsMainWindowClass))
#define BOOTSTRAPINGPROJECT_WIDGETS_IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOOTSTRAPINGPROJECT_WIDGETS_TYPE_MAIN_WINDOW))
#define BOOTSTRAPINGPROJECT_WIDGETS_IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOOTSTRAPINGPROJECT_WIDGETS_TYPE_MAIN_WINDOW))
#define BOOTSTRAPINGPROJECT_WIDGETS_MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOOTSTRAPINGPROJECT_WIDGETS_TYPE_MAIN_WINDOW, BootstrapingprojectWidgetsMainWindowClass))

typedef struct _BootstrapingprojectWidgetsMainWindow BootstrapingprojectWidgetsMainWindow;
typedef struct _BootstrapingprojectWidgetsMainWindowClass BootstrapingprojectWidgetsMainWindowClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _BootstrapingprojectMainController {
	GObject parent_instance;
	BootstrapingprojectMainControllerPrivate * priv;
	BootstrapingprojectWidgetsMainWindow* window;
};

struct _BootstrapingprojectMainControllerClass {
	GObjectClass parent_class;
};


static gpointer bootstrapingproject_main_controller_parent_class = NULL;

GType bootstrapingproject_main_controller_get_type (void) G_GNUC_CONST;
GType bootstrapingproject_widgets_main_window_get_type (void) G_GNUC_CONST;
enum  {
	BOOTSTRAPINGPROJECT_MAIN_CONTROLLER_DUMMY_PROPERTY
};
BootstrapingprojectMainController* bootstrapingproject_main_controller_new (void);
BootstrapingprojectMainController* bootstrapingproject_main_controller_construct (GType object_type);
BootstrapingprojectWidgetsMainWindow* bootstrapingproject_widgets_main_window_new (BootstrapingprojectMainController* controller);
BootstrapingprojectWidgetsMainWindow* bootstrapingproject_widgets_main_window_construct (GType object_type, BootstrapingprojectMainController* controller);
static void bootstrapingproject_main_controller_finalize (GObject* obj);


BootstrapingprojectMainController* bootstrapingproject_main_controller_construct (GType object_type) {
	BootstrapingprojectMainController * self = NULL;
	BootstrapingprojectWidgetsMainWindow* _tmp0_;
	BootstrapingprojectWidgetsMainWindow* _tmp1_;
#line 29 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/MainController.vala"
	self = (BootstrapingprojectMainController*) g_object_new (object_type, NULL);
#line 31 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/MainController.vala"
	_tmp0_ = bootstrapingproject_widgets_main_window_new (self);
#line 31 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/MainController.vala"
	g_object_ref_sink (_tmp0_);
#line 31 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/MainController.vala"
	_g_object_unref0 (self->window);
#line 31 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/MainController.vala"
	self->window = _tmp0_;
#line 33 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/MainController.vala"
	_tmp1_ = self->window;
#line 33 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/MainController.vala"
	gtk_widget_show_all ((GtkWidget*) _tmp1_);
#line 29 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/MainController.vala"
	return self;
#line 94 "MainController.c"
}


BootstrapingprojectMainController* bootstrapingproject_main_controller_new (void) {
#line 29 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/MainController.vala"
	return bootstrapingproject_main_controller_construct (BOOTSTRAPINGPROJECT_TYPE_MAIN_CONTROLLER);
#line 101 "MainController.c"
}


static void bootstrapingproject_main_controller_class_init (BootstrapingprojectMainControllerClass * klass) {
#line 25 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/MainController.vala"
	bootstrapingproject_main_controller_parent_class = g_type_class_peek_parent (klass);
#line 25 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/MainController.vala"
	G_OBJECT_CLASS (klass)->finalize = bootstrapingproject_main_controller_finalize;
#line 110 "MainController.c"
}


static void bootstrapingproject_main_controller_instance_init (BootstrapingprojectMainController * self) {
}


static void bootstrapingproject_main_controller_finalize (GObject* obj) {
	BootstrapingprojectMainController * self;
#line 25 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/MainController.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, BOOTSTRAPINGPROJECT_TYPE_MAIN_CONTROLLER, BootstrapingprojectMainController);
#line 27 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/MainController.vala"
	_g_object_unref0 (self->window);
#line 25 "/home/gwen/Programmation/vala/vala-bootstrapping-project/libtoolproject/lib/MainController.vala"
	G_OBJECT_CLASS (bootstrapingproject_main_controller_parent_class)->finalize (obj);
#line 126 "MainController.c"
}


/**
 * A controller class for managing the main window.
 */
GType bootstrapingproject_main_controller_get_type (void) {
	static volatile gsize bootstrapingproject_main_controller_type_id__volatile = 0;
	if (g_once_init_enter (&bootstrapingproject_main_controller_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (BootstrapingprojectMainControllerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) bootstrapingproject_main_controller_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (BootstrapingprojectMainController), 0, (GInstanceInitFunc) bootstrapingproject_main_controller_instance_init, NULL };
		GType bootstrapingproject_main_controller_type_id;
		bootstrapingproject_main_controller_type_id = g_type_register_static (G_TYPE_OBJECT, "BootstrapingprojectMainController", &g_define_type_info, 0);
		g_once_init_leave (&bootstrapingproject_main_controller_type_id__volatile, bootstrapingproject_main_controller_type_id);
	}
	return bootstrapingproject_main_controller_type_id__volatile;
}



